AnalyticsAccount:
  property_id: '348530916'
  key_path: 'data/input/google_analytics_service-account-key.json'

AnalyticsReport:
  dimensions_names: ['country', 'date', 'pageTitle', 'deviceCategory']
  metrics: ['activeUsers']
